# ~/.bashrc: executed by bash(1) for non-login shells.

# Note: PS1 and umask are already set in /etc/profile. You should not
# need this unless you want different defaults for root.
# PS1='${debian_chroot:+($debian_chroot)}\h:\w\$ '
# umask 022

# You may uncomment the following lines if you want `ls' to be colorized:
# export LS_OPTIONS='--color=auto'
# eval "`dircolors`"
# alias ls='ls $LS_OPTIONS'
# alias ll='ls $LS_OPTIONS -l'
# alias l='ls $LS_OPTIONS -lA'
#
# Some more alias to avoid making mistakes:
# alias rm='rm -i'
# alias cp='cp -i'
# alias mv='mv -i'


alias vhost='vim /etc/hosts'
alias vbashrc='vim ~/.bashrc'
alias sbashrc='source ~/.bashrc'
alias ll='ls -al'
alias cmo='chmod -R 777 *'
alias ..='cd ..'
alias ...='..;..'
alias rmc='rm -rf ./*'
alias dug='du -sh * | grep G'
alias dum='du -sh * | grep M'
alias cl='crontab -l'
alias ce='crontab -e'
alias phpini='php --ini'
alias cdhtdocs='cd /data/code/website'
alias cdvhost='cd /etc/nginx/conf.d'
alias cdnginxlog='cd /data/log/nginx'
alias ci="composer install -vvv --profile --prefer-dist"
alias cu="composer update -vvv --profile --prefer-dist"
alias gs='git status'
alias gl='git pull'
alias gp='git push'
alias ga='git add *; git add -f .gitignore'
alias gb='git branch'
alias gk='git checkout'
alias gkm='git checkout master'
alias gc='git commit -a -m "automate_submit"'
alias go='git clone'
alias gr='git remote -v'
alias gg='git log --graph --pretty=oneline --abbrev-commit'
alias gradd='git remote set-url --add '